theme: jekyll-theme-cayman
title: RingRoad Blog
description: Diverse topics related post are pubilshed and can be accessed via simple interface. Ranging from computer science, technology, current affairs, etc..
author: Naveen V
paginate: 10
show_downloads: false
logo: "logo.png"
google_analytics: UA-161608422-1
auto: true
permalink: pretty
repository: RingRoad-Banglore/blog
pagination:
    enabled: true
    debug: false
    collection: 'posts'
    per_page: 10
    permalink: '/page/:num/'
    title: ':title - page :num'
    limit: 0
    
plugins:
    - jekyll-seo-tag
    - jekyll-paginate